version: '3'
services:
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=deskmate
      - PGDATA=/pgdata

  api:
    build:
      context: ./server
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./server:/go/src/github.com/tylerconlee/Deskmate/server
    depends_on: 
      - db
    ports:
      - "5000:8080"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=15
      - WAIT_HOST_CONNECT_TIMEOUT=30
    links:
      - db

  graphql:
    build:
      context: ./graphql
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./graphql:/go/src/github.com/tylerconlee/Deskmate/graphql
    ports:
      - "6000:8090"

  frontend:
    build:
      context: ./client
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./client/src:/client/src 
    ports:
      - "3000:3000"
