version: 2.1
orbs:
  node: circleci/node@4.5.0
  go: circleci/go@1.6.0
jobs:
  build-client:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "./client/package-lock.json" }}
      - node/install-packages:
          app-dir: ./client
          override-ci-command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "./client/package-lock.json" }}
          paths:
            - ./client/node_modules
      - run: cat ./client/package.json #to be replaced with tests later
  build-server:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/tylerconlee/Deskmate/server
    steps:
      - checkout
      - go/load-cache
      - go/mod-download-cached
      - go/save-cache
      - run: go vet
      - run: go test -v ./...

workflows:
  version: 2
  front:
    jobs:
      - build-client
      - build-server